package halamanutama;

import barang.Barang_Owner;
import transaksijual.TR_Jual_Owner;
import transaksibeli.TR_Beli_Owner;
import Member_Owner.Member;
import login.Login_New;
import halamanutama.Laporan_Owner;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class Laporan_Owner extends javax.swing.JFrame {
 private static final String DB_URL = "jdbc:mysql://127.0.0.1/umkm";
    private static final String USER = "root";
    private static final String PASS = "";
     private final NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
    
    // Variables to store financial data
    private double totalPemasukan = 0;
    private double totalPengeluaran = 0;
    private double totalKeuntungan = 0;
    /**
     * Creates new form Dashboard_Owner
     */
    public Laporan_Owner() {
        initComponents();
        this.setExtendedState(Laporan_Owner.MAXIMIZED_BOTH);
          initTables();
        loadTransaksiJual();
        loadTransaksiBeli();
        calculateFinancialSummary();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabell_trbeli = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_trjual = new javax.swing.JTable();
        pemasukan = new javax.swing.JTextField();
        pengeluaran = new javax.swing.JTextField();
        untung = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btndashboard = new javax.swing.JButton();
        btnbarang = new javax.swing.JButton();
        btntrjual = new javax.swing.JButton();
        btntrbeli = new javax.swing.JButton();
        btnmember = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabell_trbeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "kode pembelian", "tanggal pembelian", "jumlah pembalian", "harga barang", "total harga", "no ktp supplier", "id barang"
            }
        ));
        jScrollPane1.setViewportView(tabell_trbeli);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 330, 670, 370));

        tabel_trjual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "kode penjualan", "tanggal penjualan", "harga jasa", "jenis kendaraan", "status", "plat nomor", "id barang", "id member"
            }
        ));
        jScrollPane2.setViewportView(tabel_trjual);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 670, 370));
        getContentPane().add(pemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 810, 210, 40));
        getContentPane().add(pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 810, 190, 40));
        getContentPane().add(untung, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 920, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/laporan dashboard owner.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        btndashboard.setText("jButton1");
        btndashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btndashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, 110));

        btnbarang.setText("jButton2");
        btnbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbarangActionPerformed(evt);
            }
        });
        getContentPane().add(btnbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 330, 170, 130));

        btntrjual.setText("jButton3");
        btntrjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrjualActionPerformed(evt);
            }
        });
        getContentPane().add(btntrjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 490, 170, 90));

        btntrbeli.setText("jButton4");
        btntrbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrbeliActionPerformed(evt);
            }
        });
        getContentPane().add(btntrbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 160, 110));

        btnmember.setText("jButton5");
        btnmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmemberActionPerformed(evt);
            }
        });
        getContentPane().add(btnmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 760, 170, 100));

        btnlogout.setText("jButton6");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1740, 20, 130, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private void initTables() {
        // Initialize Transaksi Jual table
        DefaultTableModel modelJual = new DefaultTableModel();
        modelJual.addColumn("Kode Penjualan");
        modelJual.addColumn("Tanggal");
        modelJual.addColumn("Harga Jasa");
        modelJual.addColumn("Jenis Kendaraan");
        modelJual.addColumn("Status");
        modelJual.addColumn("Plat Nomor");
        modelJual.addColumn("ID Barang");
        modelJual.addColumn("ID Member");
        tabel_trjual.setModel(modelJual);
        
        // Initialize Transaksi Beli table
        DefaultTableModel modelBeli = new DefaultTableModel();
        modelBeli.addColumn("Kode Pembelian");
        modelBeli.addColumn("Tanggal");
        modelBeli.addColumn("Jumlah");
        modelBeli.addColumn("Harga Barang");
        modelBeli.addColumn("Total Harga");
        modelBeli.addColumn("No KTP Supplier");
        modelBeli.addColumn("ID Barang");
        tabell_trbeli.setModel(modelBeli);
    }
    
    private void loadTransaksiJual() {
 DefaultTableModel model = (DefaultTableModel) tabel_trjual.getModel();
        model.setRowCount(0); // Clear existing data
        
        try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS)) {
            String sql = "SELECT * FROM transaksi_jual ORDER BY tanggal_penjualan DESC";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                Object[] row = {
                    rs.getString("kode_penjualan"),
                    rs.getDate("tanggal_penjualan"),
                    rs.getDouble("harga_jasa"),
                    rs.getString("jenis_kendaraan"),
                    rs.getString("status"),
                    rs.getString("Plat_Nomor"),
                    rs.getString("Id_Barang"),
                    rs.getString("id_member")
                };
                model.addRow(row);
                
                // Add to total pemasukan
                totalPemasukan += rs.getDouble("harga_jasa");
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error loading transaksi jual data: " + e.getMessage(), 
                    "Database Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Load data from transaksi_beli table
     */
    private void loadTransaksiBeli() {
        DefaultTableModel model = (DefaultTableModel) tabell_trbeli.getModel();
        model.setRowCount(0); // Clear existing data
        
        try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS)) {
            String sql = "SELECT * FROM transaksi_beli ORDER BY tanggal_pembelian DESC";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                Object[] row = {
                    rs.getString("kode_pembelian"),
                    rs.getDate("tanggal_pembelian"),
                    rs.getInt("Jumlah_pembelian"),
                    rs.getDouble("Harga_Barang"),
                    rs.getDouble("total_harga"),
                    rs.getString("No_Ktp_supplier"),
                    rs.getString("Id_Barang")
                };
                model.addRow(row);
                
                // Add to total pengeluaran
                double totalHarga = rs.getDouble("total_harga");
                if (!rs.wasNull()) {
                    totalPengeluaran += totalHarga;
                }
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error loading transaksi beli data: " + e.getMessage(), 
                    "Database Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
      private void calculateFinancialSummary() {
        // Calculate profit
        totalKeuntungan = totalPemasukan - totalPengeluaran;
        
        // Format and display values
        pemasukan.setText(currencyFormat.format(totalPemasukan));
        pengeluaran.setText(currencyFormat.format(totalPengeluaran));
        untung.setText(currencyFormat.format(totalKeuntungan));
        
        // Make text fields read-only
        pemasukan.setEditable(false);
        pengeluaran.setEditable(false);
        untung.setEditable(false);
    }
    private void btndashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashboardActionPerformed

    }//GEN-LAST:event_btndashboardActionPerformed

    private void btnbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbarangActionPerformed
         Barang_Owner b = new Barang_Owner();
        b.setVisible(true);
    }//GEN-LAST:event_btnbarangActionPerformed

    private void btntrjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrjualActionPerformed
          TR_Jual_Owner tr = new TR_Jual_Owner();
        tr.setVisible(true);
    }//GEN-LAST:event_btntrjualActionPerformed

    private void btntrbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrbeliActionPerformed
        TR_Beli_Owner tb = new TR_Beli_Owner();
        tb.setVisible(true);
    }//GEN-LAST:event_btntrbeliActionPerformed

    private void btnmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmemberActionPerformed
        Member m = new Member();
        m.setVisible(true);
    }//GEN-LAST:event_btnmemberActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
       int pilihan = JOptionPane.showConfirmDialog(this, 
            "Apakah anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION);
            
    if (pilihan == JOptionPane.YES_OPTION) {
        this.dispose();
        
        Login_New loginFrame = new Login_New();
        loginFrame.setVisible(true);
    }
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan_Owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbarang;
    private javax.swing.JButton btndashboard;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmember;
    private javax.swing.JButton btntrbeli;
    private javax.swing.JButton btntrjual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pemasukan;
    private javax.swing.JTextField pengeluaran;
    private javax.swing.JTable tabel_trjual;
    private javax.swing.JTable tabell_trbeli;
    private javax.swing.JTextField untung;
    // End of variables declaration//GEN-END:variables
}
