/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package transaksibeli;
import barang.Barang_Owner;
import transaksijual.TR_Jual_Owner;
import transaksibeli.TR_Beli_Owner;
import Member_Owner.Member;
import login.Login_New;
import halamanutama.Laporan_Owner;
import TAMBAH.Tambah;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author LENOVO
 */
public class TR_Beli_Owner extends javax.swing.JFrame {

    /**
     * Creates new form TR_Beli_Owner
     */
    public TR_Beli_Owner() {
        initComponents();
        this.setExtendedState(TR_Beli_Owner.MAXIMIZED_BOTH); 
        loadTransaksiBeli();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabell_trbeli = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btndashboard = new javax.swing.JButton();
        btntrjual = new javax.swing.JButton();
        btnbarang = new javax.swing.JButton();
        btnmember = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabell_trbeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "kode pembelian", "tanggal pembelian", "jumlah pembalian", "harga barang", "total harga", "no ktp supplier", "id barang"
            }
        ));
        tabell_trbeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabell_trbeliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabell_trbeli);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 930, 570));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transaksi beli owner.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        btn_hapus.setText("jButton2");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 650, 250, 90));

        btn_tambah.setText("jButton1");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1355, 533, 250, 90));

        btndashboard.setText("jButton1");
        btndashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btndashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 90));

        btntrjual.setText("jButton2");
        btntrjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrjualActionPerformed(evt);
            }
        });
        getContentPane().add(btntrjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 150, 120));

        btnbarang.setText("jButton3");
        btnbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbarangActionPerformed(evt);
            }
        });
        getContentPane().add(btnbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 170, 120));

        btnmember.setText("jButton4");
        btnmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmemberActionPerformed(evt);
            }
        });
        getContentPane().add(btnmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 170, 100));

        btnlogout.setText("jButton4");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 30, 170, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   private void loadTransaksiBeli() {
        DefaultTableModel model = (DefaultTableModel) tabell_trbeli.getModel();
        model.setRowCount(0); // Clear existing data
        
        try {
            Connection conn = koneksi.koneksiDB();
            // Change the SQL query to target the correct table
            String sql = "SELECT * FROM transaksi_beli";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                Object[] row = {
                    rs.getString("kode_pembelian"),
                    rs.getDate("tanggal_pembelian"),
                    rs.getInt("Jumlah_pembelian"),
                    rs.getDouble("Harga_Barang"),
                    rs.getDouble("total_harga"),
                    rs.getString("No_Ktp_supplier"),
                    rs.getString("Id_Barang")
                };
                model.addRow(row);
            }
            
            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(this, 
                "Error loading data: " + e.getMessage(), 
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
        
    private void btndashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashboardActionPerformed
        Laporan_Owner d = new Laporan_Owner();
        d.setVisible(true);
    }//GEN-LAST:event_btndashboardActionPerformed

    private void btntrjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrjualActionPerformed
        TR_Jual_Owner tr = new TR_Jual_Owner();
        tr.setVisible(true);
    }//GEN-LAST:event_btntrjualActionPerformed

    private void btnbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbarangActionPerformed
        Barang_Owner b = new Barang_Owner();
        b.setVisible(true);
    }//GEN-LAST:event_btnbarangActionPerformed

    private void btnmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmemberActionPerformed
        Member m = new Member();
        m.setVisible(true);
    }//GEN-LAST:event_btnmemberActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(this, 
            "Apakah anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION);
            
    if (pilihan == JOptionPane.YES_OPTION) {
        this.dispose();
        
        Login_New loginFrame = new Login_New();
        loginFrame.setVisible(true);
    }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        Tambah T = new Tambah();
        T.setVisible(true);
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
       int selectedRow = tabell_trbeli.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                "Pilih transaksi yang akan dihapus terlebih dahulu!", 
                "Perhatian", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Anda yakin ingin menghapus transaksi ini?", 
            "Konfirmasi Hapus", 
            JOptionPane.YES_NO_OPTION);
            
        if (confirm == JOptionPane.YES_OPTION) {
            String kodePembelian = tabell_trbeli.getValueAt(selectedRow, 0).toString();
            
            try {
                Connection conn = koneksi.koneksiDB();
                String sql = "DELETE FROM transaksi_beli WHERE kode_pembelian = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, kodePembelian);
                
                int rowsAffected = stmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, 
                        "Transaksi berhasil dihapus!", 
                        "Sukses", 
                        JOptionPane.INFORMATION_MESSAGE);
                    loadTransaksiBeli(); // Refresh the table
                } else {
                    JOptionPane.showMessageDialog(this, 
                        "Gagal menghapus transaksi!", 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);
                }
                
                stmt.close();
                conn.close();
            } catch (SQLException e) {
                System.err.println("Got an exception! ");
                System.err.println(e.getMessage());
                JOptionPane.showMessageDialog(this, 
                    "Error menghapus data: " + e.getMessage(), 
                    "Database Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tabell_trbeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabell_trbeliMouseClicked
                                               
    int selectedRow = tabell_trbeli.getSelectedRow();
    if (selectedRow != -1) {
        
        String kodePembelian = tabell_trbeli.getValueAt(selectedRow, 0).toString();
        
        try {
            Connection conn = koneksi.koneksiDB();
            String sql = "SELECT * FROM transaksi_beli WHERE kode_pembelian = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, kodePembelian);
            ResultSet rs = stmt.executeQuery();
            
            if (rs.next()) {
              
                StringBuilder details = new StringBuilder();
                details.append("Detail Transaksi Pembelian\n\n");
                details.append("Kode Pembelian: ").append(rs.getString("kode_pembelian")).append("\n");
                details.append("Tanggal Pembelian: ").append(rs.getDate("tanggal_pembelian")).append("\n");
                details.append("Jumlah Pembelian: ").append(rs.getInt("Jumlah_pembelian")).append("\n");
                details.append("Harga Barang: Rp ").append(String.format("%,.2f", rs.getDouble("Harga_Barang"))).append("\n");
                details.append("Total Harga: Rp ").append(String.format("%,.2f", rs.getDouble("total_harga"))).append("\n");
                details.append("No KTP Supplier: ").append(rs.getString("No_Ktp_supplier")).append("\n");
                details.append("ID Barang: ").append(rs.getString("Id_Barang")).append("\n");
                
                JOptionPane.showMessageDialog(this, 
                    details.toString(), 
                    "Detail Transaksi", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
            
            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(this, 
                "Error mengambil data: " + e.getMessage(), 
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_tabell_trbeliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TR_Beli_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TR_Beli_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TR_Beli_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TR_Beli_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TR_Beli_Owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btnbarang;
    private javax.swing.JButton btndashboard;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmember;
    private javax.swing.JButton btntrjual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabell_trbeli;
    // End of variables declaration//GEN-END:variables
}
