/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;
import koneksi.koneksi;
import login.Login_New;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
 import javax.swing.*;
/**
 *  
 * @author lendr
 */
public class login_awal extends javax.swing.JFrame {

    /**
     * Creates new form login_awal
     */
    public login_awal() {
        initComponents();
         this.setExtendedState(login_awal.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttondashboard = new javax.swing.JButton();
        buttonbarang = new javax.swing.JButton();
        buttontransaksijual = new javax.swing.JButton();
        buttontransaksibeli = new javax.swing.JButton();
        buttonmember = new javax.swing.JButton();
        buttonmasuk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1922, 1080));
        setSize(new java.awt.Dimension(1922, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Dashboard Owner.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1922, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(1922, 1080));
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1920, 1110));

        buttondashboard.setText("jButton1");
        buttondashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondashboardActionPerformed(evt);
            }
        });
        getContentPane().add(buttondashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, 100));

        buttonbarang.setText("jButton2");
        buttonbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbarangActionPerformed(evt);
            }
        });
        getContentPane().add(buttonbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 170, 90));

        buttontransaksijual.setText("jButton3");
        buttontransaksijual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttontransaksijualActionPerformed(evt);
            }
        });
        getContentPane().add(buttontransaksijual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 433, 170, 100));

        buttontransaksibeli.setText("jButton4");
        buttontransaksibeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttontransaksibeliActionPerformed(evt);
            }
        });
        getContentPane().add(buttontransaksibeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 590, 170, 90));

        buttonmember.setText("jButton5");
        buttonmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmemberActionPerformed(evt);
            }
        });
        getContentPane().add(buttonmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 713, 170, 90));

        buttonmasuk.setText("jButton6");
        buttonmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmasukActionPerformed(evt);
            }
        });
        getContentPane().add(buttonmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 893, 200, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttondashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondashboardActionPerformed
      JOptionPane.showMessageDialog(this, "Harap melakukan login terlebih dahulu", "Informasi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttondashboardActionPerformed

    private void buttonbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbarangActionPerformed
        JOptionPane.showMessageDialog(this, "Harap melakukan login terlebih dahulu", "Informasi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonbarangActionPerformed

    private void buttontransaksijualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttontransaksijualActionPerformed
       JOptionPane.showMessageDialog(this, "Harap melakukan login terlebih dahulu", "Informasi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttontransaksijualActionPerformed

    private void buttontransaksibeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttontransaksibeliActionPerformed
      JOptionPane.showMessageDialog(this, "Harap melakukan login terlebih dahulu", "Informasi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttontransaksibeliActionPerformed

    private void buttonmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmemberActionPerformed
       JOptionPane.showMessageDialog(this, "Harap melakukan login terlebih dahulu", "Informasi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonmemberActionPerformed

    private void buttonmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmasukActionPerformed
      Login_New b  = new Login_New();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonmasukActionPerformed

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_awal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonbarang;
    private javax.swing.JButton buttondashboard;
    private javax.swing.JButton buttonmasuk;
    private javax.swing.JButton buttonmember;
    private javax.swing.JButton buttontransaksibeli;
    private javax.swing.JButton buttontransaksijual;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
