/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trjual_karyawan;
import Barang_karyawan.Barang_Karyawan_New;
import Member_Karyawan.Member_Karyawan;
import javax.swing.JOptionPane;
import login.Login_New;
import trjual_karyawan.TR_Jual_Karyawan;
import halamanutama1.Dashboard_Karyawan;

import Barang_karyawan.Barang_Karyawan_New;

/**
 *
 * @author LENOVO
 */
public class TR_Jual_Karyawan extends javax.swing.JFrame {

 
    public TR_Jual_Karyawan() {
        initComponents();
        this.setExtendedState(TR_Jual_Karyawan.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnmember = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnbarang = new javax.swing.JButton();
        btndashboard = new javax.swing.JButton();
        button_mobil = new javax.swing.JButton();
        button_motor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kendaraan karyawan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnmember.setText("jButton3");
        btnmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmemberActionPerformed(evt);
            }
        });
        getContentPane().add(btnmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 160, 80));

        btnlogout.setText("jButton4");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1760, 20, 120, 90));

        btnbarang.setText("jButton1");
        btnbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbarangActionPerformed(evt);
            }
        });
        getContentPane().add(btnbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 160, 90));

        btndashboard.setText("jButton1");
        btndashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btndashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 100));

        button_mobil.setText("jButton1");
        button_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_mobilActionPerformed(evt);
            }
        });
        getContentPane().add(button_mobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 600, 480));

        button_motor.setText("jButton2");
        button_motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_motorActionPerformed(evt);
            }
        });
        getContentPane().add(button_motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 420, 600, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbarangActionPerformed
        Barang_Karyawan_New bk = new Barang_Karyawan_New();
        bk.setVisible(true);
    }//GEN-LAST:event_btnbarangActionPerformed

    private void btnmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmemberActionPerformed
        Member_Karyawan mk = new Member_Karyawan();
        mk.setVisible(true);
    }//GEN-LAST:event_btnmemberActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(this,
            "Apakah anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION);

        if (pilihan == JOptionPane.YES_OPTION) {
            this.dispose();

            Login_New loginFrame = new Login_New();
            loginFrame.setVisible(true);
        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btndashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashboardActionPerformed
        Dashboard_Karyawan dk = new Dashboard_Karyawan();
        dk.setVisible(true);
    }//GEN-LAST:event_btndashboardActionPerformed

    private void button_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_mobilActionPerformed
     TR_Jual_Karyawan_mobil1 trk = new TR_Jual_Karyawan_mobil1 ();
        trk.setVisible(true);
    }//GEN-LAST:event_button_mobilActionPerformed

    private void button_motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_motorActionPerformed
     trj_motor_karyawan trk = new trj_motor_karyawan();
        trk.setVisible(true);
    }//GEN-LAST:event_button_motorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TR_Jual_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TR_Jual_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TR_Jual_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TR_Jual_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TR_Jual_Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbarang;
    private javax.swing.JButton btndashboard;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmember;
    private javax.swing.JButton button_mobil;
    private javax.swing.JButton button_motor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
