/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package barang;
import barang.Barang_Owner;
import transaksijual.TR_Jual_Owner;
import transaksibeli.TR_Beli_Owner;
import Member_Owner.Member;
import login.Login_New;
import halamanutama.Laporan_Owner;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

import Barang_karyawan.Barang_Karyawan_New;

/**
 *
 * @author LENOVO
 */
public class Barang_Owner extends javax.swing.JFrame {

    /**
     * Creates new form Barang_Owner
     */
    public Barang_Owner() {
        initComponents();
        this.setExtendedState(Barang_Owner.MAXIMIZED_BOTH);
         loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btndashboard = new javax.swing.JButton();
        btntrjual = new javax.swing.JButton();
        btntrbeli = new javax.swing.JButton();
        btnmember = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_barang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        tabel_barang.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id_Barang", "Nama_Barang", "Jumlah_Barang", "Harga_Barang", "Total_Harga", "No_KTP"
            }
        ));
        jScrollPane2.setViewportView(tabel_barang);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 1450, 430));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/barang owner.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1930, 1080));

        btndashboard.setText("jButton1");
        btndashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btndashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 183, 170, 90));

        btntrjual.setText("jButton2");
        btntrjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrjualActionPerformed(evt);
            }
        });
        getContentPane().add(btntrjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 170, 120));

        btntrbeli.setText("jButton3");
        btntrbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrbeliActionPerformed(evt);
            }
        });
        getContentPane().add(btntrbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 170, 120));

        btnmember.setText("jButton4");
        btnmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmemberActionPerformed(evt);
            }
        });
        getContentPane().add(btnmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 170, 100));

        btnlogout.setText("jButton4");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 40, 170, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void loadData() {
        DefaultTableModel model = (DefaultTableModel) tabel_barang.getModel();
        model.setRowCount(0);
        try {
            Connection conn = koneksi.koneksiDB();
            String sql = "SELECT * FROM barang";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                String idBarang = rs.getString("Id_Barang");
                String namaBarang = rs.getString("Nama_Barang");
                int jumlahBarang = rs.getInt("Jumlah_Barang");
                double hargaBarang = rs.getDouble("Harga_Barang");
                double totalHarga = rs.getDouble("Total_Harga");
                String noKtp = rs.getString("No_Ktp");
                
                model.addRow(new Object[]{idBarang, namaBarang, jumlahBarang, hargaBarang, totalHarga, noKtp});
            }
            
            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
    }
    private void btndashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashboardActionPerformed
      Laporan_Owner d = new Laporan_Owner();
        d.setVisible(true);
    }//GEN-LAST:event_btndashboardActionPerformed

    private void btntrjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrjualActionPerformed
         TR_Jual_Owner tr = new TR_Jual_Owner();
        tr.setVisible(true);
    }//GEN-LAST:event_btntrjualActionPerformed

    private void btntrbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrbeliActionPerformed
         TR_Beli_Owner tb = new TR_Beli_Owner();
        tb.setVisible(true);
    }//GEN-LAST:event_btntrbeliActionPerformed

    private void btnmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmemberActionPerformed
       Member m = new Member();
        m.setVisible(true);
    }//GEN-LAST:event_btnmemberActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
       int pilihan = JOptionPane.showConfirmDialog(this, 
            "Apakah anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION);
            
    if (pilihan == JOptionPane.YES_OPTION) {
        this.dispose();
        
        Login_New loginFrame = new Login_New();
        loginFrame.setVisible(true);
    }
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang_Owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndashboard;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmember;
    private javax.swing.JButton btntrbeli;
    private javax.swing.JButton btntrjual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel_barang;
    // End of variables declaration//GEN-END:variables
}
